void cutscene() {
        int b;
                for(int a = 4; a >= 1; a--) {
                        clear();
                        attron(COLOR_PAIR(16 - ((a - 1) * 4)));
        printw("Once a day...");
                attroff(COLOR_PAIR(16 - ((a - 1) * 4)));
                refresh();
                if(a == 1) {
                        napms(3000);
                } else {
                napms(500);
                }
                }
                for(int a = 1; a <= 4; a++) {
                        clear();
                        attron(COLOR_PAIR(16 - ((a - 1) * 4)));
        printw("Once a day...");
                attroff(COLOR_PAIR(16 - ((a - 1) * 4)));
                refresh();
                if(a == 1) {
                        napms(3000);
                } else {
                napms(500);
                }
                }
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(5000);
                clear();
                printw("##########v##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(200);
                clear();
                printw("##########@##########\n");
                printw("#         v         #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(200);
                clear();
                printw("########## ##########\n");
                printw("#         @         #\n");
                printw("#         v         #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(200);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#         @         #\n");
                printw("#         v         #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(200);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @         #\n");
                printw("#         v       # #\n");
                printw("#                   #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(200);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(2000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("# What's that, prof?#\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(3000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("# A machine to...   #\n");
                printw("#####################\n");
                refresh();
                napms(3000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#   To what, prof?  #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("# A machine to...   #\n");
                printw("#####################\n");
                refresh();
                napms(3000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #<&           #\n");
                printw("#     #           # #\n");
                printw("#to explore 1D world#\n");
                printw("#####################\n");
                refresh();
                napms(4000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("# 1D world? Really? #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(2000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     # <&        # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(200);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #  <&       # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(2000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #   ^         #\n");
                printw("#     #   &       # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(2000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#        ?!?        #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #   ^         #\n");
                printw("#     #   &       # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(2000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #   ^         #\n");
                printw("#     #   &       # #\n");
                printw("# I need guinea pig #\n");
                printw("#####################\n");
                refresh();
                napms(3000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#        So?        #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #   ^         #\n");
                printw("#     #   &       # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(4000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#        So?        #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #   &>      # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(1000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #    &>     # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(1000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #     &>    # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(1000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #      &>   # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(1000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #       &>  # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(1000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #       ^     #\n");
                printw("#     #       &   # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v         #\n");
                printw("#     #       ^   # #\n");
                printw("#     #       &     #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @       # #\n");
                printw("#         v   ^     #\n");
                printw("#     #       &   # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @   ^   # #\n");
                printw("#         v   &     #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#             ^     #\n");
                printw("#         @   &   # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(50);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#         @  <&   # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#     Wait, what?   #\n");
                printw("#         @ <&    # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#     Wait, what?   #\n");
                printw("#         @<&     # #\n");
                printw("#         v         #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#     Wait, what?   #\n");
                printw("#                 # #\n");
                printw("#         @<&       #\n");
                printw("#     #   v       # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#     Wait, what?   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #  <@<&     # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#     Wait, what?   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     # <@<&      # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#     Wait, what?   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #<@<&       # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#        NO!!!      #\n");
                printw("#     #@<&        # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(100);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#        NO!!!      #\n");
                printw("#     #<&         # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(3000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #<&         # #\n");
                printw("#     #             #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(3000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #           # #\n");
                printw("#     #<&           #\n");
                printw("#     #           # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(1000);
                clear();
                printw("########## ##########\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                   #\n");
                printw("#                 # #\n");
                printw("#                   #\n");
                printw("#     #           # #\n");
                printw("#     #             #\n");
                printw("#     #<&         # #\n");
                printw("#                   #\n");
                printw("#####################\n");
                refresh();
                napms(3000);


}
void cutscene2(int id, int index) {
        clear();
        std::string view = "";
                for(int j = (index < 3 ? 0 : index - 3); j <= ([&]() -> int {
                                if(index >= cond.size() - 1 - 5) {
                                return cond.size() - 1;
                                } else {
                                return index + 5;
                                }
                                })(); j++) {
                        view += std::string(cond[j] == 'c' ? "[@]" : (cond[j] != '0' ? "[X]" : "[ ]")) + " ";
                }
                view.pop_back();

                napms(2000);
                printw("Me: Where Am I?\n");
                refresh();
                napms(3000);
                printw("Professor: In 1D World\n");
                refresh();
                napms(4000);
                clear();
                printw("Me: Why you threw me here?\n");
                refresh();
                napms(5000);
                printw("Professor: Like I said, I need guinea pig. It's you\n");
                refresh();
                napms(7000);
                clear();
                printw("Me: Why you don't tell me before throw me?\n");
                refresh();
                napms(5000);
                printw("Professor: I too excited, It's first my discovery\n");
                refresh();
                napms(7000);
                clear();
                printw("Me: Why you always say \"first discovery\" every your discovery? Prof, this is the 286th your discovery, not first\n");
                refresh();
                napms(8000);
                printw("Professor: I don't know.\n");
                refresh();
                napms(3000);
                clear();
                printw("Me: You even don't tell me how to survival in this world\n");
                refresh();
                napms(5000);
                printw("Professor: Okay, first, you need to know, your body is actually near me, only your consciousness is put there.\n");
                refresh();
                napms(7000);
                clear();
                printw("Me: If this is not my body, when I killed here, I still alive?\n");
                refresh();
                napms(7000);
                printw("Professor: No, you still die. This is your consciousness, without that, you can't alive. Just fight them, don't be next to that.\n");
                refresh();
                napms(7000);
                clear();
                printw("%s\n", view.c_str());
                napms(1000);
                printw("Me: I see something, what's that?\n");
                refresh();
                napms(5000);
                printw("Professsor: That is your environment.\n");
                refresh();
                napms(5000);
                clear();
                printw("%s\n", view.c_str());
                printw("Me: I don't understand.\n");
                refresh();
                napms(3000);
                printw("Professor: Simply put, it's a map to show you the situation around you.\n");
                refresh();
                napms(8000);
                clear();
                addch('#'| COLOR_PAIR(id));
                printw("\n\n");
                printw("%s\n", view.c_str());
                refresh();
                napms(3000);
                printw("Me: I see something else, what's this?\n");
                refresh();
                napms(5000);
                printw("Professor: It's your right indication. Green mean safe, red mean danger, white mean you can pick it.\n");
                refresh();
                napms(7000);
                clear();
                addch('#'| COLOR_PAIR(id));
                printw("\n\n");
                printw("%s\n", view.c_str());
                printw("Me: I don't understand\n");
                refresh();
                napms(3000);
                printw("Professor: You'll understand. Your task is collect 200 block\n");
                refresh();
                napms(8000);
		clear();
		printw("Me: Why you choose me?\n");
		refresh();
		napms(1000);
		printw("Professor: JUST GET BACK AND DO WHAT YOU SHOULD DO!\n");
		refresh();
		napms(5000);
                clear();
		printw("Me: Why?\n");
                refresh();
                napms(3000);
		printw("Professor: I have some important jobs.\n");
		refresh();
		napms(7000);
		clear();
                printw("Why I have a crazy professor.\n");
                refresh();
                napms(5000);
                clear();
}

void goodEnding() {
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(5000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #>          # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #@>         # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     # @>        # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #  @>       # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #    @>     # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(200);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #     @>    # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(400);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(5000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#  Welcome back     #\n");
        printw("#####################\n");
        refresh();
        napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @    # #\n");
        printw("#     #      v      #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(1000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @    # #\n");
        printw("#     #      v      #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: Why you threw me?");
        refresh();
        napms(400);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @    # #\n");
        printw("#     #      v      #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: Why you threw me?\n");
	printw("Professor: Because I too excited.");
        refresh();
        napms(2000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @    # #\n");
        printw("#     #      v      #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: Excited because you can survive.");
        refresh();
        napms(5000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @    # #\n");
        printw("#     #      v      #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: What?");
        refresh();
        napms(5000);
                for(int a = 1; a <= 4; a++) {
                        clear();
                        attron(COLOR_PAIR(16 - ((a - 1) * 4)));
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @    # #\n");
        printw("#     #      v      #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: What?");
                attroff(COLOR_PAIR(16 - ((a - 1) * 4)));
                refresh();
                if(a == 1) {
                        napms(3000);
                } else {
                napms(500);
                }
                }
		clear();
		printw("Thank you for the compliment...?");
		refresh();
		napms(5000);
		clear();
		refresh();
		napms(3000);
		printw("Good ending.");
		refresh();
		napms(5000);
}

void badEnding() {
	clear(); 
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(5000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: I PASSED MY MISSION!");
        refresh();
        napms(5000);
	for(int i = 0; i < 4; ++i) {
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: HHAHAHHAAHHAHHAHAHAHA!!!!");
        refresh();
        napms(500);
	clear();
	attron(COLOR_PAIR(17));
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: HHAHAHHAAHHAHHAHAHAHA!!!!");
        refresh();
        napms(500);
	attroff(COLOR_PAIR(17));
	}
	for(int i = 0; i < 4; ++i) {
	clear();
        
        
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#######<&############\n");
        printw("#####################\n");
        printw("#####################\n");
	printw("Professor: HHAHAHHAAHHAHHAHAHAHA!!!!");
        refresh();
        napms(500);
	clear();
	attron(COLOR_PAIR(17));
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#######<&############\n");
        printw("#####################\n");
        printw("#####################\n");
	printw("Professor: HHAHAHHAAHHAHHAHAHAHA!!!!");
        refresh();
        napms(500);
	attroff(COLOR_PAIR(17));
	}
	clear();
	refresh();
	napms(4500);
	printw("I.threw.was'nt.because.excitedness.");
	refresh();
	napms(5000);
	clear();
	printw("Bad ending.");
	refresh();
	napms(5000);
	clear();
	printw("SCP-256");
	refresh();
	napms(5000);

}

void badEnding2() {
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(5000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #>          # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #@>         # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     # @>        # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #  @>       # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #    @>     # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(200);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #     @>    # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(400);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(5000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @>   # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      &    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(4000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @>   # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      &    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: At the end, I should end this,");
        refresh();
        napms(5000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @>   # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      &    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("manually");
        refresh();
        napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#       [CENSORED]  #\n");
        printw("#     # [CENSORED]# #\n");
        printw("#     #      ^      #\n");
        printw("#     #      &    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: NOOOOOOO!");
        refresh();
        napms(3000);
	clear();
	for(int i = 0; i < 3; i++) {
	clear();
	attron(COLOR_PAIR(17));
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#       [CENSORED]  #\n");
        printw("#     # [CENSORED]# #\n");
        printw("#     #      ^      #\n");
        printw("#     #      &    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: NOOOOOOO!");
        refresh();
        napms(4000);
	clear();
	attroff(COLOR_PAIR(17));
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#       [CENSORED]  #\n");
        printw("#     # [CENSORED]# #\n");
        printw("#     #      ^      #\n");
        printw("#     #      &    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: NOOOOOOO!");
        refresh();
        napms(100);
	}
	for(int i = 0; i < 3; i++) {
	clear();
	attron(COLOR_PAIR(17));
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#       [CENSORED]  #\n");
        printw("#     # [CENSORED]# #\n");
        printw("#     #      ^      #\n");
        printw("#     #      &    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: NOOOOOOO!");
        refresh();
        napms(100);
	clear();
	attroff(COLOR_PAIR(17));
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#       [CENSORED]  #\n");
        printw("#     # [CENSORED]# #\n");
        printw("#     #      ^      #\n");
        printw("#     #      &    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: NOOOOOOO!");
        refresh();
        napms(4000);
	}
	clear();
	printw("I have a phobia of blood, but I should to do this.");
	refresh();
	napms(5000);
	clear();
	refresh();
	napms(3000);
	printw("Bad Ending 2.");
	refresh();
	napms(5000);
	clear();

}

void truthEnding() {
	clear(); 
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(5000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: NO,"); 
        refresh();
        napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     # ^           #\n");
        printw("#     # &         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: NO,"); 
        refresh();
        napms(200);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     # &>        # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: NO,"); 
        refresh();
        napms(200);
	for(int i = 0; i < 30; i++) {
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     # ^           #\n");
        printw("#     # &         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: NO, NOOOO!"); 
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#         ^         #\n");
        printw("#         &       # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: NO, NOOOO!"); 
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #<&         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: NO, NOOOO!"); 
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #       &>  # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: NO, NOOOO!"); 
        refresh();
        napms(100);
	}
	for(int i = 0; i < 30; i++) {
	clear();
        
        
        printw("########## ##########\n");
        printw("#   &    >          #\n");
        printw("#             >     #\n");
        printw("#   ^            &  #\n");
        printw("#      &    &     # #\n");
        printw("#                   #\n");
        printw("#     #       v   # #\n");
        printw("# &    # ^   v      #\n");
        printw("#     # &         # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: NO, NOOOO!"); 
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#    &              #\n");
        printw("#         ^         #\n");
        printw("#         &       # #\n");
        printw("#   &          &    #\n");
        printw("#     #           # #\n");
        printw("#     #     v  v    #\n");
        printw("#   &  #          # #\n");
        printw("#              .    #\n");
        printw("#####################\n");
	printw("Professor: NO, NOOOO!"); 
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#   <       &     & #\n");
        printw("#         &   &     #\n");
        printw("#                 # #\n");
        printw("#    v     ^        #\n");
        printw("#     #           # #\n");
        printw("#     #     >       #\n");
        printw("#  &   #<&        # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: NO, NOOOO!"); 
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#    &        v     #\n");
        printw("#          &    &   #\n");
        printw("#       ^         # #\n");
        printw("#   < &       & ^   #\n");
        printw("#     #           # #\n");
        printw("#  &   #   &        #\n");
        printw("#     #       &>  # #\n");
        printw("#    >              #\n");
        printw("#####################\n");
	printw("Professor: NO, NOOOO!"); 
        refresh();
        napms(100);
	}
	clear();
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
        printw("#####################\n");
	refresh();
	napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(5000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #>          # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #@>         # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     # @>        # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #  @>       # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(100);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #    @>     # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(200);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #     @>    # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(400);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                 # #\n");
        printw("#                   #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
        refresh();
        napms(5000);
	clear();
	printw("I just remembered, the professor had been gone for a long time. Who is he? How did his discovery come?");
	refresh();
	napms(7000);
	clear();
	printw("That's not professor.");
	refresh();
	napms(3000);
	clear();
	printw("Safe entity was warning me.");
	refresh();
	napms(4000);
	clear();
	printw("Over and over.");
	refresh();
	napms(3000);
	clear();
	printw("But, who is he?");
	refresh();
	napms(3000);
	clear();
	printw("I think he is me.");
	refresh();
	napms(3000);
	clear();
	printw("That's the clone of me.");
	refresh();
	napms(3000);
	clear();
	printw("That's me, who hate me.");
	refresh();
	napms(3000);
	clear();
	printw("But why he try to kill me?");
	refresh();
	napms(5000);
	clear();
	printw("Because the professor incident?");
	refresh();
	napms(5000);
	clear();
	printw("If I save professor...");
	refresh();
	napms(5000);
	clear();
	printw("Maybe the clone of me will not hate me.");
	refresh();
	napms(5000);
	clear();
	printw("And this won't happen.");
	refresh();
	napms(3000);
	clear();
	printw("But the reality say not.");
	refresh();
	napms(5000);
	clear();
	printw("I'm not loyal, I can't, I'm useless.");
	refresh();
	napms(5000);
	clear();
	printw("I deserve to be replaced. But it's too late.");
	refresh();
	napms(5000);
	clear();
	printw("I know his strategy.");
	refresh();
	napms(5000);
	clear();
	printw("He use professor's first discovery.");
	refresh();
	napms(3000);
	clear();
	printw("To kill me.");
	refresh();
	napms(3000);
	clear();
	printw("And replace me.");
	refresh();
	napms(3000);
	clear();
	printw("Replace a man who can't save his mentor.");
	refresh();
	napms(3000);
	clear();
	printw("His name is...");
	refresh();
	napms(5000);
	clear();
	refresh();
	napms(5000);
	clear();
	printw("SCP-256.");
	refresh();
	napms(7000);
	clear();
	printw("Truth Ending.");
	refresh();
	napms(6000);
	clear();
	printw("Professor: Hello? Are you okay?");
	refresh();
	napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	refresh();
	napms(2000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: WHAT?");
	refresh();
	napms(2000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: AM I DREAMING?");
	refresh();
	napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: What's your mean?");
	refresh();
	napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: I think you...");
	refresh();
	napms(500);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: I think you...\n");
	printw("Professor: Was killed?");
	refresh();
	napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("You're right.");
	refresh();
	napms(5000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	refresh();
	napms(2000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: My plan was success");
	refresh();
	napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #      @>   # #\n");
        printw("#     #             #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	refresh();
	napms(1000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      @>     #\n");
        printw("#     #           # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	refresh();
	napms(1000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #             #\n");
        printw("#     #      @>   # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	refresh();
	napms(1000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	refresh();
	napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: WHAT?!");
	refresh();
	napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: A PRANK?!");
	refresh();
	napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me:A PRANK?!\n");
	printw("Professor: Yeah.");
	refresh();
	napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	refresh();
	napms(2000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: I ALMOST KILLED BECAUSE YOUR PRANK!!!");
	refresh();
	napms(5000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: What's your mean?");
	refresh();
	napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: SCP-256 WANT KILL ME!");
	refresh();
	napms(5000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: I think he was pranked too");
	refresh();
	napms(5000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: I think I've talked about this to SCP-256...");
	refresh();
	napms(8000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: I'm not sure.");
	refresh();
	napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: I think you forgot to talk it to SCP-256.");
	refresh();
	napms(5000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	refresh();
	napms(4000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: Now, where he is?");
	refresh();
	napms(5000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: HE WAS GONE BECAUSE YOU!");
	refresh();
	napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: I know, my mistake.");
	refresh();
	napms(3000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Professor: Sorry for threaten your life.");
	refresh();
	napms(5000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	refresh();
	napms(5000);
	clear();
        printw("########## ##########\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#                   #\n");
        printw("#            &    # #\n");
        printw("#            v      #\n");
        printw("#     #           # #\n");
        printw("#     #      ^      #\n");
        printw("#     #      @    # #\n");
        printw("#                   #\n");
        printw("#####################\n");
	printw("Me: I forgive you.");
	refresh();
	napms(5000);
	clear();
	printw("The real truth ending.\n");
	refresh();
	napms(3000);
	clear();
	printw("Professor: By the way, I wasn't actually eaten by the SCP-255, I was teleporting to beach. As planned...\n");
	refresh();
	napms(10000);
	printw("Me: I hope you don't forget next time.\n");
	refresh();
	napms(5000);
	clear();
	printw("Me: Wait, SCP-255?\n");
	refresh();
	napms(5000);
	clear();
}

void cutscene3() {
	clear();
	refresh();
	napms(3000);
	printw("Professor: My system detects Dangerous Entities will be more aggressive. Be Careful.\n");
	refresh();
	napms(5000);
	printw("Me: Why you threw me here?\n");
	refresh();
	napms(1000);
	clear();
	printw("Professor: Because I too excited.\n");
	refresh();
	napms(5000);
	printw("Me: Prof, how long do you want to answer like that?\n");
	refresh();
	napms(5000);
	clear();
	printw("Professor: Until you make a decision\n");
	refresh();
	napms(3000);
	clear();
	printw("Me: W-what?\n");
	refresh();
	napms(3000);
	printw("Professor: Any question?\n");
	refresh();
	napms(3000);
	clear();
	printw("Me: What do you mean with that?\n");
	refresh();
	napms(500);
	printw("Professor: I think not. Okay, goodbye!\n");
	refresh();
	napms(3000);
	clear();
	printw("Me: What do you mean with that?\n");
	refresh();
	napms(3000);
	clear();
	printw("What's going on here?\n");
	refresh();
	napms(5000);
	clear();
}

void credit() {
	clear();
	printw("Where Am I game.");
	refresh();
	napms(5000);
	clear();
	printw("Programmer: Rizky");
	refresh();
	napms(5000);
	clear();
	printw("Cutscenes: Rizky");
	refresh();
	napms(5000);
	clear();
	printw("Music: Your imagination");
	refresh();
	napms(5000);
	clear();
	printw("Idea: Rizky");
	refresh();
	napms(5000);
	clear();
	printw("Where Am I game.");
	refresh();
	napms(5000);
}

